dist: trusty
language: clojure
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get install -y nodejs
  - sudo npm install jsonlint -g

script:
  - cd cljs-src; lein with-profile +test doo phantom once
  - jsonlint gooreplacer.gson
